markdown: rdiscount
pygments: true
paginate: 15
permalink: "/:title"

base_url: "http://engineering.outright.com"
email: code@outright.com

facebook_appid: 167848943333883
facebook_num_posts: 5
facebook_width: 580
facebook_colorscheme: light

ga_code: UA-88530-22

author_ids: [bcurren, trobrock, ravasthi]
authors:
  bcurren:
    display_name: Ben Curren
    gravatar: 7530e528c21181f8e893ec445f15a199
    email: ben@outright.com
    web: http://jotthought.com
    twitter: bcurren
    github: bcurren
  trobrock:
    display_name: Trae Robrock
    gravatar: 71c3bbda60a46a241bf9a2d68e41cbec
    email: trae@outright.com
    web: http://trobrock.com
    twitter: trobrock
    github: trobrock
  ravasthi:
    display_name: Richa Avasthi
    gravatar: b13527b475f29568229f083c5a3cb2ce
    email: richa@outright.com
    web: http://richa.avasthi.name
    twitter: ravasthi
    github: ravasthi

# Local server
auto: true
server: true
server_port: 4000

# Excludes
exclude: [bin, styles, CNAME, Gemfile, Gemfile.lock, Guardfile, README.md, Vendorfile]

# # Calculate gravatar hash from email address
# def calc_gravatar(email)
#   require 'digest/md5'
#   Digest::MD5.hexdigest(email.downcase.strip)
# end
# calc_gravatar("ben@outright.com")
